### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ajjxf** [SpotlightKid/miditk-smf#15]
could you please explain the way to install&use it more clearly?

thanks :)

**Comment by SpotlightKid** [comment]
What exactly do you want to know? The [README](https://github.com/SpotlightKid/miditk-smf/blob/master/README.md) has the basic info about installing the package and some examples, more examples are in the [examples](https://github.com/SpotlightKid/miditk-smf/tree/master/examples) directory.

**Comment by ajjxf** [comment]
after reading README--quickstart--install ,i still dont know how to install it.
![屏幕截图 2022-12-28 081748](https://user-images.githubusercontent.com/109795978/209739035-1ecffd20-d2ab-4880-aa02-50c89d82e35b.png)
what is pip  and how to use it?
thanks :)

**Comment by SpotlightKid** [comment]
`pip` is the Python package installer. Everyone developing with Python needs to know it.

https://packaging.python.org/en/latest/tutorials/installing-packages/

**Comment by ajjxf** [comment]
thanks for the reply and have a nice day     :)
