### ISSUE TITLE
Writing System-exclusive data crashes with TypeError

### ISSUE THREAD

**Issue by jkbd** [SpotlightKid/miditk-smf#7]
With Python 3.10.8 the following code unfortunately crashes on calling `MidiFileWriter.system_exclusive()`:
```
import tempfile
from miditk.smf import MidiFileWriter

with tempfile.NamedTemporaryFile(mode='wb', suffix='.mid',
                                 prefix='score-', delete=False) as smf:
    midi = MidiFileWriter(smf)
    midi.header(format=0, num_tracks=1, tick_division=96)
    midi.start_of_track(track=0)
    microsec_per_quarter_note = 500000
    midi.tempo(microsec_per_quarter_note)

    midi.system_exclusive(b'Trigger the crash.') # ...BOOM

    midi.end_of_track()
    midi.eof()
```
The traceback on my Linux box is:
```
Traceback (most recent call last):
  File "/home/jakob/Dokumente/prg/Python3/synth_replicator/minimal.py", line 16, in <module>
    midi.system_exclusive(b'Trigger the crash.')
  File "/home/jakob/.local/lib/python3.10/site-packages/miditk/smf/writer.py", line 146, in system_exclusive
    self.event_slice(tobytestr(SYSTEM_EXCLUSIVE) + sysex_len + data +
TypeError: unsupported operand type(s) for +: 'int' and 'bytes'
```
I guess, a valid solution would be to use `write_bew` from `miditk.smf.converters`, like:
```
number = 42
valid = write_bew(number, length=2) + b'data'
```
But I am not sure about the endianess and the `length`.

**Comment by SpotlightKid** [comment]
Thanks for the report. However that part of the code was changed in the meanwhile. Unfortunately I haven't done a release in a long while, so the changes are not in a releases version yet.

If you are able, I would appreciate if you could test your use case with the current version in git.

**Comment by jkbd** [comment]
Looking at
https://github.com/SpotlightKid/miditk-smf/blob/528e4ae594f98ee37d4ec02d043766856f618c41/miditk/smf/writer.py#L55-L58
is that compliant with the standard to write the SysEx-chunk-size? From what I read (e.g. here http://www.ccarh.org/courses/253/handout/smf/), the unique manufacturer ID would be expected as the second byte.

**Comment by jkbd** [comment]
> I would appreciate if you could test your use case with the current version in git.

I will try.

**Comment by SpotlightKid** [comment]
> is that compliant with the standard to write the SysEx-chunk-size?

The [source I was referring to](http://www.somascape.org/midi/tech/mfile.html#sysex) seems to disagree with yours. I'll double check with the actual standard.

**Comment by jkbd** [comment]
Thank you for the reference! I don't trust the link I posted a lot. It was just a quick search on the internet.

I uninstalled my `miditk-smf` pip package, cloned this repository and ran the code above inside the repository, so the `import` works. Same result: `TypeError`.

**Comment by SpotlightKid** [comment]
Are you sure your code is using the version from the repo? Can you copy+paste the new exception traceback?

**Comment by jkbd** [comment]
Sure.
```
$ git log | head -n1
commit 528e4ae594f98ee37d4ec02d043766856f618c41
$ python minimal.py 
Traceback (most recent call last):
  File "/home/jakob/Downloads/github/miditk-smf/minimal.py", line 21, in <module>
    midi.system_exclusive(b'Trigger the crash.')
  File "/home/jakob/Downloads/github/miditk-smf/miditk/smf/writer.py", line 177, in system_exclusive
    self.sysex_slice(data)
  File "/home/jakob/Downloads/github/miditk-smf/miditk/smf/writer.py", line 57, in sysex_slice
    self.event_slice(tobytestr(SYSTEM_EXCLUSIVE) + sysex_len + data +
TypeError: unsupported operand type(s) for +: 'int' and 'bytes'
```
Elsewere the package can not be found:
```
$ cd /tmp
$ cp path/to/minimal.py .
$ python minimal.py 
Traceback (most recent call last):
  File "/tmp/minimal.py", line 5, in <module>
    from miditk.smf import MidiFileWriter
ModuleNotFoundError: No module named 'miditk'
```
Still, you are more of a Python-wizard than me and I could do something wrong.

**Comment by jkbd** [comment]
I think, this is actually the problem, not the chunk-size:
```
> python
>>> from miditk.common.constants import SYSTEM_EXCLUSIVE
>>> type(tobytestr(SYSTEM_EXCLUSIVE))
<class 'int'>
```

**Comment by SpotlightKid** [comment]
Yes, I forgot the brackets around `SYSTEM_EXCLUSIVE` and `END_OF_EXCLUSIVE`.

Fix incoming later.

**Comment by jkbd** [comment]
Awesome! I'll stay tuned.
